example = 0

# Returns the exact data type of the specified object
type()

# Outputs the specified data to the standard output (console)
print()

# Reads user input from the console and returns it as a string
input()

# Converts a specified value (e.g., a string or float) into an integer data type
int()

# Rounds a number. Arg 1: the number to evaluate. Arg 2: precision in decimal places
round(example,2)

# Returns the total number of items in a specified object (must be a sequence or collection)
# STR, LIST, TUPLE, LIST, SET
# NOT: INT, FLOAT, COMPLEX, BOOL
len()