'''
Lists are a collection of data
'''

num_list = [1,2,3,4,5]
str_list = ["Abc","Def","Ghi"]
l = []

# takes the first value "1" 
num_list[0]

# takes the last value "5"
num_list[-1]

# takes first value and ends at specified point  "1,2"
num_list[0:2]

# add item at the end of the list
l.append()

# insert element at the specific index
l.insert(2,num_list)

# remove item of sepcific value
l.remove(2)

# remove item at specific index
l.pop(0)

# sort list from min to max
l.sort()