x = 1
y = 2

'''
Comparison Operators
'''

# Checks if variables are the same
print(x==y)

# Checks if variables are not the same
print(x!=y)

# Checks if x is greater than y
print(x>y)

# Check if x is greater or equal to y
print(x>=y)

'''
Logical Operators
'''

# Checks if both conditions are true
print(x > y and x == y)

# Checks if one of the condition is true
print(x > y or x < y)

# reverse condition
print(not(x==y))

